config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "usuarios#index"

  #Rutas de Usuario Controller
  get 'usuarios/login',as: "login"
  get 'usuarios/registro',as: "registro"
  post 'usuarios/validar_sesion',as: "validar_sesion"
  post 'usuarios/salvar_registro',as: "salvar_registro"

  resources :admin_urls

  #UrlShort
  post 'dashboard',to: "admin_urls#dashboard"
  post 'obtener_short_urls',to: "admin_urls#obtener_short_urls"
  post 'create_short_url',to: "admin_urls#create_short_url"
  post 'almacenar_datos_request',to: "admin_urls#almacenar_datos_request" 
  post 'remove_short_url', to: "admin_urls#remove_short_url"
  post 'obtener_info_short_url',to: "admin_urls#obtener_info_short_url" 
  get 'shortUrl/:short_url',to: "admin_urls#redirect_sitio" 

  #REST_API_KEY
  get 'obtener_todos_links',to: "admin_urls#obtener_todos_links"
  post 'crear_short_url',to: "admin_urls#crear_short_url"

end

app/models/usuario.rb
class Usuario < ApplicationRecord

	validates :email, uniqueness: true
	validates :nombre , presence: true
	validates :password, presence: true

	has_many :admin_urls

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :usuario_autenticado,:except => [:login,:validar_sesion,:registro,:salvar_registro]

  def login
  end

  def index
  end

  def registro
  end

  def salvar_registro

    if Usuario.exists?(email: params[:email])
      render json: "{estatus:'NOK'}", status: :precondition_failed
    else
        usuario = Usuario.new
        usuario.nombre = params[:nombre]
        usuario.email = params[:email]
        usuario.password = params[:password]
        usuario.apikey = SecureRandom.base58(24)
        usuario.save
        session[:usuario_id] = usuario.usuario
        #respond_to do |format|
          #format.html {redirect_to root_path, info: 'Registro correcto' }
        #end
        if usuario.save
          render json: "{estatus:'OK'}", status: :created
        else
          render json: "{estatus:'NOK'}", status: :bad_request
        end
    end


  end

  def validar_sesion
  	usuario = Usuario.where(:email=>params[:email],:password=>params[:password])
  	if(usuario.count()==1)
  		session[:usuario_id] = usuario[0]['id']
  		#respond_to do |format|
      #		format.html {redirect_to root_path, info: 'Login correcto' }
    	#end
      render json: '{"estatus":"OK","email":"'+usuario[0]['email']+'","nombre":"'+usuario[0]['nombre']+'","apikey":"'+usuario[0]['apikey']+'"}', status: :ok
  	else
  		session[:usuario_id] = nil
        render json: "{estatus:'NOK'}", status: :not_found
  	end
  end

end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/index.html.erb
<h1>Usuarios#index</h1>
<p>Find me in app/views/usuarios/index.html.erb</p>

app/views/usuarios/login.html.erb
<center>
<%= form_for("usuario", :url => validar_sesion_path,:html =>{:onSubmit=>'return validate();',:id=>'nuevo_usuario'}) do |f| %>

<div class="field">
    <%= f.label "Correo Electrónico" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" ,class: "form-control" , required: true%>
  </div>

  <div class="field">
    <%= f.label "Contraseña" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "new-password",class: "form-control" , required: true%>
  </div>

  <div class="actions">
    <%= f.submit "Guardar",class: "btn btn-primary btn-lg", data: { disable_with: false }  %>
  </div>


  <% end %>

  </center>

app/views/usuarios/registro.html.erb
<center>
<%= form_for("usuario", :url => salvar_registro_path,:html =>{:onSubmit=>'return validate();',:id=>'nuevo_usuario'}) do |f| %>

<div class="field">
    <%= f.label "Nombre" %>
    <%= f.text_field :nombre , required: true%>
  </div>

<div class="field">
    <%= f.label "Email" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" ,class: "form-control" , required: true%>
  </div>

  <div class="field">
    <%= f.label "Contraseña" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "new-password",class: "form-control" , required: true%>
  </div>

  <div class="actions">
    <%= f.submit "Guardar",class: "btn btn-primary btn-lg", data: { disable_with: false }  %>
  </div>


  <% end %>

  </center>